name: Auto Commit and Push Workflow
on:
  schedule:
    - cron: '0 */1 * * *'  # Exécution automatique toutes les heures
  workflow_dispatch:  # Déclenchement manuel

jobs:
  commit:
    runs-on: ubuntu-latest  # Environnement d'exécution

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Vérifie le repository actuel

      - name: Set up Git user
        run: |
          echo "Configuring Git user..."
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Update Log File
        run: |
          echo "Updating log with the current date..." 
          echo "$(date) - Update successful" >> update.py
          
      - name: Check if there are changes
        run: |
          echo "Checking for changes before committing..."
          git diff --exit-code || echo "Changes detected!"

      - name: Commit and Push if changes exist
        run: |
          if git diff --exit-code; then
            echo "No changes to commit"
          else
            git add update.py
            git commit -m "Auto-commit on $(date)"  # Message de commit avec timestamp
            git push origin main
            echo "Changes pushed to the main branch"  # Confirmation du push

      - name: Completion message
        run: |
          echo "GitHub Action completed successfully! All steps were executed."
